package publish

import (
	"fmt"
	"log"
	"os/exec"
)

// PublishToGitHub stages, commits, and pushes the content to GitHub.
func PublishToGitHub() error {
	commands := [][]string{
		{"git", "add", "."},
		{"git", "commit", "-m", "New blog post generated by ChatGPT"},
		{"git", "push", "origin", "main"},
	}

	for _, command := range commands {
		cmd := exec.Command(command[0], command[1:]...)
		output, err := cmd.CombinedOutput()
		if err != nil {
			return fmt.Errorf("command %s failed: %w - output: %s", command[0], err, output)
		}
	}

	log.Println("Content published to GitHub!")
	return nil
}
